server:
  port: 8888

spring:
  cloud:
    config:
      server:
        #native:
          #search-locations: file:///${user.home}/ead/authuser,  file:///${user.home}/ead/course
        git:
          uri: 'https://github.com/edersonjseder/ead-config-server-repo'
          default-label: main
          username: edersonjseder
          password: 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
  #Datasource
  datasource:
    url: "jdbc:postgresql://localhost:5432/ead-config-server?currentSchema=sc_config_server&autoreconnect=true"
    username: edersonjseder
    password: Postgres1756
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non-contextual-creation: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

ead:
  config-server:
    username: configserver
    password: 'ead123cs'
    authority: 'ROLE_ADMIN'
  service-registry:
    username: serviceregistry
    password: 'ead123sr'
    authority: 'ROLE_ADMIN'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.service-registry.username}:${ead.service-registry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
